import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/helpers/ClientLayout";
import { Providers } from "@/helpers/Providers";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "ByteLocker",
  description: "Generated by Team Sanghatan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased `}
      >
        <Providers>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
